[action] process template

diff --git a/deploy/manifests/kubeapps-tests.yaml b/deploy/manifests/kubeapps-tests.yaml
--- a/deploy/manifests/kubeapps-tests.yaml
+++ b/deploy/manifests/kubeapps-tests.yaml
@@ -9,16 +9,29 @@ metadata:
 spec:
   containers:
     - name: kubeapps-assetsvc-test
-      image: bitnami/nginx:1.16.1-debian-10-r27
+      image: docker.io/bitnami/nginx:1.19.2-debian-10-r1
       env:
         - name: ASSETSVC_HOST
           value: kubeapps-internal-assetsvc.altemistahub
         - name: ASSETSVC_PORT
           value: "8080"
       command:
-        - sh
+        - bash
         - -c
-        - curl -o /tmp/output $ASSETSVC_HOST:$ASSETSVC_PORT/v1/charts && cat /tmp/output && cat /tmp/output | grep wordpress
+        # We are requesting the "wordpress" chart to the chartsvc to check that everything works as expected
+        # Also, we retry several times in case the repository is being populated at the time of executing this test
+        - |
+            n=0
+            until [ "$n" -ge 5 ]; do
+              if curl -o /tmp/output $ASSETSVC_HOST:$ASSETSVC_PORT/v1/ns/altemistahub/charts && cat /tmp/output && cat /tmp/output | grep wordpress; then
+                break
+              fi
+              sleep 10
+              ((n+=1))
+            done
+            if [ "$n" -eq 5 ]; then
+              exit 1
+            fi
   restartPolicy: Never
 
 ---
@@ -32,7 +45,7 @@ metadata:
 spec:
   containers:
     - name: kubeapps-dashboard-test
-      image: bitnami/nginx:1.16.1-debian-10-r27
+      image: docker.io/bitnami/nginx:1.19.2-debian-10-r1
       env:
         - name: DASHBOARD_HOST
           value: kubeapps.altemistahub
